package meta

import (
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
)

const modulePath = "github.com/kimjooyoon/gooo-meta-operator-typechecker"

func GenerateGoSource(ir IR) ([]byte, error) {
	if err := ValidateIR(ir); err != nil {
		return nil, err
	}
	irRaw, err := json.MarshalIndent(ir, "", "  ")
	if err != nil {
		return nil, err
	}
	proofJSON := make([]string, 0, len(ir.Proofs))
	for _, proof := range ir.Proofs {
		raw, marshalErr := json.Marshal(proof)
		if marshalErr != nil {
			return nil, marshalErr
		}
		proofJSON = append(proofJSON, string(raw))
	}
	var source string
	source += "// Code generated by gooo-meta-operator-typechecker compile; DO NOT EDIT.\n"
	source += "package generated\n\n"
	source += "import (\n\t\"encoding/json\"\n\t\"fmt\"\n\n\tmeta \"" + modulePath + "/internal/meta\"\n)\n\n"
	source += "const (\n\tSemanticSourceDigest = " + strconv.Quote(ir.SourceDigest) + "\n\tSemanticContractDigest = " + strconv.Quote(ir.ContractDigest) + "\n\tSemanticIRDigest = " + strconv.Quote(ir.IRDigest) + "\n)\n\n"
	source += "const SemanticIRJSON = " + strconv.Quote(string(irRaw)) + "\n\n"
	source += "var proofJSON = map[string]string{\n"
	for index, proof := range ir.Proofs {
		source += "\t" + strconv.Quote(proof.CaseID) + ": " + strconv.Quote(proofJSON[index]) + ",\n"
	}
	source += "}\n\n"
	source += "func ProofFor(caseID string) (meta.Proof, bool) {\n"
	source += "\traw, ok := proofJSON[caseID]\n\tif !ok { return meta.Proof{}, false }\n"
	source += "\tvar proof meta.Proof\n\tif err := json.Unmarshal([]byte(raw), &proof); err != nil { return meta.Proof{}, false }\n"
	source += "\treturn proof, true\n}\n\n"
	source += "func Execute(caseID string, input meta.FixtureInput) (meta.ExecutionResult, error) {\n"
	source += "\tproof, ok := ProofFor(caseID)\n\tif !ok { return meta.ExecutionResult{}, fmt.Errorf(\"unknown generated proof %q\", caseID) }\n"
	source += "\treturn meta.ExecuteProof(proof, input)\n}\n"
	return format.Source([]byte(source))
}

func WriteCompileOutputs(sourcePath, contractPath, outputIR, outputGo string) (IR, error) {
	source, err := ParseSource(sourcePath)
	if err != nil {
		return IR{}, err
	}
	contract, err := LoadContract(contractPath)
	if err != nil {
		return IR{}, err
	}
	ir, err := BuildIR(source, contract)
	if err != nil {
		return IR{}, err
	}
	generated, err := GenerateGoSource(ir)
	if err != nil {
		return IR{}, err
	}
	if err := writeCallerFile(outputIR, mustJSON(ir)); err != nil {
		return IR{}, err
	}
	if err := writeCallerFile(outputGo, generated); err != nil {
		return IR{}, err
	}
	return ir, nil
}

func mustJSON(value any) []byte {
	raw, _ := json.MarshalIndent(value, "", "  ")
	return append(raw, '\n')
}

func LoadIR(path string) (IR, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return IR{}, err
	}
	var ir IR
	if err := json.Unmarshal(raw, &ir); err != nil {
		return IR{}, err
	}
	return ir, nil
}

func writeCallerFile(path string, raw []byte) error {
	if path == "" || !filepath.IsAbs(path) {
		return errors.New("compile outputs must be absolute caller-owned paths")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, raw, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
